### ISSUE TITLE
scripts populate ansible-hydra/hosts [ec2hosts] even when a different hosts file is specified on command line

### ISSUE THREAD

**Issue by hackartisan** [curationexperts/ansible-hydra#90] opened 2015-12-23 14:36 UTC
e.g., using the submodule pattern and a 'hosts' file in the superproject.

we tried changing dest to {{ inventory_file }} but that doesn't change this behavior:
https://github.com/curationexperts/ansible-hydra/blob/master/roles/launch_ec2/tasks/main.yml#L34

**Comment by acozine** [comment] 2017-03-03 18:22
@hackmastera I reproduced this today, then did some further testing. With nothing in `ansible.cfg` about host files, I can make the `launch_ec2` role update a hosts file in a different directory by using the `fix_hosts` branch and passing the inventory file twice on the command line:
`ansible-playbook -i /path/to/test_hosts my_playbook.yml --extra-vars inventory_file=/path/to/test_hosts`
I'll see if I can simplify, but would this solution work for you?

**Comment by acozine** [comment] 2017-03-03 18:34
The link in the original comment is stale - the proposed solution is here: 
https://github.com/curationexperts/ansible-hydra/blob/fix_hosts/roles/launch_ec2/tasks/main.yml#L54

**Comment by hackartisan** [comment] 2017-03-03 18:37
@acozine oh interesting. It's been a while so I actually don't think I have a full grasp of the context of this. I wonder if @sanfordd remembers why we needed to do it, and/or what our workaround ended up being, and whether we would want to go back to doing it this way.

**Comment by hackartisan** [comment] 2017-03-03 18:40
I suspect our workaround was manual, and that this solution is definitely better. It would be nice to not have to pass it twice, but your solution makes sense.

When you say "with nothing in ansible.cfg" you imply there's a different behavior if you're using ansible.cfg; is there a way to shorten the command by using a .cfg? And remind me, can a .cfg file life with the project or does it have to be in a user's home directory?

**Comment by acozine** [comment] 2017-03-03 19:31
I'm using `ansible.cfg`, but I'm not specifying an inventory file there. I haven't tested an `ansible.cfg` setting like `inventory = /Users/me/ansible-projects/hosts` with this branch. It might well override the `-i` flag and/or the `{{ inventory_file }}` variable. Or the variable might override the config setting. If that's a use case, I can do more testing. 

There's a default global ansible.cfg but you can also have a per-project one, and I believe the project-specific config overrides the global one on your local machine. On my laptop, I only use project-specific ones to avoid confusion.

**Comment by sanfordd** [comment] 2017-04-26 15:44
It looks like we had this sorted at some point, we're getting the new machines to pop up in newboxes when they're built. I'm going to close this one.

**Closed as completed by sanfordd** 2017-04-26 15:44 UTC
